error: package directory 'my_python_package' does not exist
